// Generated by scripts/generate-release-channel.mjs.
// Production packaging overwrites this value from CODEXGPT_BRIDGE_UPDATE_MANIFEST_URL.
export const BUNDLED_UPDATE_MANIFEST_URL: string | undefined = undefined;
